### ISSUE TITLE
Consider adding the Rands slack to the community section

### ISSUE THREAD

**Issue by testdrivendavid** [jordan-cutler/path-to-senior-engineer-handbook#22]
Consider adding the line below to the `## Communities` Section

`- [Leadership Community (Slack)](https://randsinrepose.com/welcome-to-rands-leadership-slack/)`

**Comment by jordan-cutler** [comment]
Hi @testdrivendavid , thank you for this recommendation.

Added it here: https://github.com/jordan-cutler/path-to-senior-engineer-handbook/commit/2e2bc39357fc6c026efda52f2cac5a605c44e4b2

Appreciate you!
