### ISSUE TITLE
One of the recommended authors is no longer relevant

### ISSUE THREAD

**Issue by BrendanL79** [jordan-cutler/path-to-senior-engineer-handbook#25]
John Sonmez has no current information on the software industry, having been drummed out of it years ago for a pattern of behavior that would have violated this repo's code of conduct. His book is already almost a decade old and will likely not be seeing further updates. Consider removing it from the list.

**Comment by jordan-cutler** [comment]
Hi @BrendanL79 .

Thank you for bringing this up and having the care & attention to let me know respectfully.

I removed it from the README here: https://github.com/jordan-cutler/path-to-senior-engineer-handbook/commit/667ff264972bdee3607cb44ff7606a81f7bb6034.

Appreciate you 🙏
