### ISSUE TITLE
Adding The Operator's Handbook to this awesome list

### ISSUE THREAD

**Issue by karkir0003** [jordan-cutler/path-to-senior-engineer-handbook#37]
Awesome list @jordan-cutler . I'd also recommend adding "The Operator's Handbook" newsletter. It also gives actionable tips to grow career and some amazing articles here worth featuring

https://open.substack.com/pub/torstenwalbaum?utm_source=share&utm_medium=android&r=18oruz

**Comment by karkir0003** [comment]
Example articles that were eye opening

https://open.substack.com/pub/torstenwalbaum/p/theres-a-right-way-to-be-wrong?utm_source=share&utm_medium=android&r=18oruz

https://open.substack.com/pub/torstenwalbaum/p/what-is-a-good-metric?utm_source=share&utm_medium=android&r=18oruz

https://open.substack.com/pub/torstenwalbaum/p/how-to-maximize-your-impact?utm_source=share&utm_medium=android&r=18oruz

**Comment by jordan-cutler** [comment]
Nice share @karkir0003 ! Added: https://github.com/jordan-cutler/path-to-senior-engineer-handbook/commit/51211b015a44f7b313145c6707aef6f083e7a7ea

**Comment by karkir0003** [comment]
> Nice share @karkir0003 ! Added: https://github.com/jordan-cutler/path-to-senior-engineer-handbook/commit/51211b015a44f7b313145c6707aef6f083e7a7ea

thanks!
