### ISSUE TITLE
Remove affiliate links as well the ones to Amazon altogether

### ISSUE THREAD

**Issue by GildedHonour** [jordan-cutler/path-to-senior-engineer-handbook#6]
One who knows the name of a book and its author, will be able to find it on his own.

**Comment by jordan-cutler** [comment]
@GildedHonour which affiliate links are you referring to?

**Comment by RishiPrakash** [comment]
@GildedHonour Affiliated links does not hurt in any case though. It's easier to have a handy link to Amazon anytime.

**Comment by GildedHonour** [comment]
@jordan-cutler in the 1st statement you get surprised as if you weren't aware, whereas in the 2nd one you explain yourself as if you were.

**Comment by jordan-cutler** [comment]
@GildedHonour I'm not sure if this is what you meant, but here's a PR to remove the "refs".

As far as I'm aware, Amazon affiliate links are always "amzn.to" links though. 

Just wanted to make it clear there were never affiliate links present
